# Generated by Django 3.2.9 on 2022-03-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Files', '0002_alter_file_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='file_path',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
