# Generated by Django 3.2.9 on 2022-03-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Files', '0003_auto_20220324_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_path',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
