# Generated by Django 3.2.9 on 2022-03-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Files', '0005_alter_file_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='file',
            name='file_path',
        ),
        migrations.AddField(
            model_name='file',
            name='metadata',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='token',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('file', 'file')], default='file', max_length=4),
            preserve_default=False,
        ),
    ]
